### ISSUE TITLE
No Unicode support

### ISSUE THREAD

**Issue by nomicode** [MacIrssi/MacIrssi#11]
I am unable to send anything other than perhaps ASCII or Latin1.

I would like to be able to send in full UTF-8.

❒ All the other encodings ✔ UTF-8

**Comment by ghost** [comment]
MacIrssi does support UTF-8, though you have to make sure your settings dialog is set as such. The Irssi core MacIrssi is based around defaults to ASCII encoding by default.

**Comment by nomicode** [comment]
Settings dialog?

I ported my old irssi config over and it doesn't seem to let me use UTF-8. I tried a bunch of /set invocations from the manual, and from friends. Nothing seemed to work. Can you tell me what I need to put in the file to get UTF-8 support for both display and sending?

**Comment by ghost** [comment]
See the option at the bottom of http://cl.ly/1ScR. Alternative "/set term_charset utf-8" will do it.

**Comment by nomicode** [comment]
Wow, is that a new setting? Thanks!

**Comment by ghost** [comment]
The UI setting has been in since the start of the 0.8.6 branch (I think). The /set command is an Irssi command and has been there since the start of time :).
