### ISSUE TITLE
bug in perl library support

### ISSUE THREAD

**Issue by atr000** [MacIrssi/MacIrssi#12]
ver:  Irssi: Client: MacIrssi 0.8.6.6 (Core:irssi 0.8.15-svn 20100617 2055)

trying to load trackbar.pl

(16:43:53) Can't load 'Contents/Resources/Scripts/auto/Irssi/TextUI/TextUI.bundle' for module Irssi::TextUI: dlopen(Contents/Resources/Scripts/auto/Irssi/TextUI/TextUI.bundle, 1): Symbol not found: _active_entry
(16:43:53)   Referenced from: /Users/atr/Applications/MacIrssi.app/Contents/Resources/Scripts/auto/Irssi/TextUI/TextUI.bundle
(16:43:53)   Expected in: flat namespace
(16:43:53)  in /Users/atr/Applications/MacIrssi.app/Contents/Resources/Scripts/auto/Irssi/TextUI/TextUI.bundle at /System/Library/Perl/5.10.0/darwin-thread-multi-2level/DynaLoader.pm line 207.
(16:43:53)  at /Users/atr/.irssi/scripts/trackbar.pl line 83
(16:43:53) Compilation failed in require at /Users/atr/.irssi/scripts/trackbar.pl line 83.
(16:43:53) BEGIN failed--compilation aborted at /Users/atr/.irssi/scripts/trackbar.pl line 83.

**Comment by ghost** [comment]
Apologies for the delay. What version of OS X were you trying this on? Perl support is a little ropey in the current builds. There's a better setup coming in the next version which has Perl modules compiled for each OS X since Tiger.

**Comment by atr000** [comment]
It was 10.6 but I was building for most of the defaults you have within the frameworks. Going the independent route definitely sounds good with how broken some of the frameworks are
