### ISSUE TITLE
Sound menu should list all installed sounds

### ISSUE THREAD

**Issue by rorya** [MacIrssi/MacIrssi#15]
Sound menus in the Preferences Notifications tab, should list sounds outside of the system domain. That is, it should also scan for sounds in the Local, User and Network domains.

**Comment by ghost** [comment]
Yeah, it probably should. Do the sound you're interested in also show up in System Preferences? Or are you just looking at being able to set arbitrary sounds?

**Comment by rorya** [comment]
Yes, as far as I can tell, the sound effects list in the Sound prefpane, in all versions of OSX list the sounds that exist in all OSX domains. So yes, in my case, most of my custom sounds are on the network domain, and those show up in the Sound prefpane.

**Comment by ghost** [comment]
Fixed in 7c02a51c9df3d803e44f305c698430f180f71a08. Though if you pick sounds on a Network volume then you might find that MacIrssi hangs trying to play sounds if your network mounts are flaky.
