### ISSUE TITLE
No alert when name mentioned

### ISSUE THREAD

**Issue by saramah** [MacIrssi/MacIrssi#16]
macirssi only seems to detect a mention when it's at the beginning of a line (eg, "sarah: seen that yet?") when it should detect a mention when it's also not, like "i think sarah knows about that bug" or "alastair sarah: coffee?"

**Comment by ghost** [comment]
Yeah, last time I looked into this in an depth I came to the conclusion that normal Irssi acts like this in its default config.

MI doesn't see anything special to detect mentions. Roughly: Irssi's core detects a mention and communicates the desired visual style for it as its being printed to the screen. Along side that, the "level" of the channel increases which causes MI to trigger a sound/growl alert.

If you can get a plain-old Irssi to act the way you're expecting and you don't see this in MacIrssi with the same config then I'd be interested in seeing the config you need to use to recreate it.

**Comment by ghost** [comment]
(I'll also have a look about the mentions and let you know if I find anything. Last time I looked I lost patience with it and gave up.)

**Comment by ghost** [comment]
So, turns out you can issue:

/hilight -nick [your nick]

To ask Irssi to highlight your nick anywhere on a given line. Will this do what you want?

**Comment by saramah** [comment]
apparently yes, chalk this up to newbishness.

**Comment by ghost** [comment]
Not so newbish if I had to look it up in the manual though. When it comes out, 0.8.7 is likely to be the last major revision I do in a while (just to sort the kinks out of the current version), I'll see if I can set up links to an FAQ and the Irssi manual in the Help menu.
