### ISSUE TITLE
Autojoin room functionality

### ISSUE THREAD

**Issue by saramah** [MacIrssi/MacIrssi#17]
In preferences, would be cool if you could list rooms to autojoin for particular servers.

**Comment by ghost** [comment]
Auto join exists. It's part of the Network tab. However, it's really badly implemented in the preferences panel at the moment. You  need to take the following steps to ensure autojoin/autosendcmd works:
1. Create a server entry
2. Create a network entry
3. Associate the server with the network
4. Add the room to the list of autojoin rooms in the Network tab.
5. Make _SURE_ you check the "Auto" box in the second column.

Then cycle your connections (or quit and reload) you should find it auto joins. I'm planning to improve the user experience of the preferences pane soon. Probably combining Networks and Servers into the same panel.

**Comment by ghost** [comment]
(Closing out as its already present, feel free to reopen it if you feel there are still issues to be addressed)
