### ISSUE TITLE
Should be able to select font for input field

### ISSUE THREAD

**Issue by ismail** [MacIrssi/MacIrssi#18]
Input field uses a hardcoded font but it would be nice to be able to configure the font for it. Using Version 0.8.6.6 (Build b05ba43)

**Comment by ghost** [comment]
I can't remember why I passed this up previously. Maybe purely out of laziness. Also, in a previous life, the entry area couldn't resize to take account of different font faces or sizes. This is no longer a restriction.

**Comment by ismail** [comment]
It would nice so I could choose a bigger font size to be anti-aliased etc. Same goes for channel titles btw but thats somewhat less important.

**Comment by ghost** [comment]
My current plan is to have the text entry field match the font you select for the message window. I'm not sure I'll change the topic area though.

**Comment by ghost** [comment]
Done in 10c1ecd46c2618c9fea3fbb48ecb0b3c6a8a018d. Enjoy.
