### ISSUE TITLE
Update to irssi 0.8.15

### ISSUE THREAD

**Issue by ismail** [MacIrssi/MacIrssi#19]
http://www.irssi.org/news/ChangeLog for the bugfixes, includes crash fixes and other annoyances. Also a new stable release along would be nice :)

**Comment by ghost** [comment]
Will do.

**Comment by ismail** [comment]
Thanks for the great work, its lovely.

**Comment by ghost** [comment]
The current "develop" HEAD contains irssi-0.8.15. It has done for a while, sorry for the delay in replying. It'll go live next time I push a release. In the mean time, if you are brave, you can run the pre-release versions from the Downloads section.

**Comment by ismail** [comment]
I am already doing so, great release so far.
