### ISSUE TITLE
Channels/PMs Under Network Window

### ISSUE THREAD

**Issue by lyetz** [MacIrssi/MacIrssi#20]
Something I'd definitely love to see implemented in MacIrssi is the ability to keep channels/PMs from a single network categorized.  Things get real messy when new PMs and channels get placed at the bottom of the list.  I currently resort to creating an empty window for each server, and manually moving all my other windows under that particular network.  It's pretty tedious to do this each time you get a new message.  Hopefully the following screenshot explains better than I did:

http://lyetz.me/uploads/irssicat.png

Regardless of whether or not this ability is added in the future, MacIrssi is an excellent client for OS X.  I really appreciate the work put into it!

Cheers!

**Comment by ghost** [comment]
Channel ordering is controlled by the irssi core; as such MacIrssi won't exert any control over ordering. I'd suggest looking into ordering via Perl scripts if you want this functionality.

**Comment by ghost** [comment]
Whoops, meant to close this at the same time.
