### ISSUE TITLE
IRC messages containing £ symbol are not transmitted to channel

### ISSUE THREAD

**Issue by gknapp** [MacIrssi/MacIrssi#22]
I've using version 0.8.6.6. When I type a sentence to a channel that contains a pound sign (£), the sentence disappears into the ether - it's not in my chat history if I push up either!

**Comment by ghost** [comment]
More than likely it's that your channel encoding isn't set to UTF8. The default Irssi (which MacIrssi honours) used to be ASCII which won't properly transmit the pound sign. Switch it to UTF8 in Preferences and you should be ok.

**Comment by gknapp** [comment]
Thanks, this sorted the issue.
