### ISSUE TITLE
Feature Request: SSL-enabled servers

### ISSUE THREAD

**Issue by macavity23** [MacIrssi/MacIrssi#24]
It would be great to have a 'Use SSL' checkbox (unchecked by default) when creating server configs in the Servers preference pane (which just applies the -ssl switch to the /connect command) so that those of us who use secure servers can add them using the GUI.

Thanks!

**Comment by ghost** [comment]
This is in the latest "develop" builds, I can't remember the exact commit where it came in. It will go live the next time I do a release.

**Comment by knowtheory** [comment]
Just an FYI, i've been tripped up by this a bit.  I just started working at a university which quarantines net connections which try to connect to IRC over unencrypted connections.  So i've been trying to figure out how to make Macirssi connect using SSL by default.

I'm just about to try the dev build, but it'd be super cool if you could push out a release w/ this :)

**Comment by ghost** [comment]
Yes, I'm hoping to have a proper release with these changes and additional Lion fixes soon.
