### ISSUE TITLE
alphabetize channel list

### ISSUE THREAD

**Issue by joewilliams** [MacIrssi/MacIrssi#27]
Is it possible to have macirssi group and alphabetize the channel list? If not possibly a config option?

Ideally it would be something like:

Console [X]
channel a
channel b
channel c
pm a
pm b
pm c

**Comment by ghost** [comment]
Channel ordering is controlled by the irssi core; as such MacIrssi won't exert any control over ordering. You're free to move these channels around using /window commands in irssi (and/or script that with perl).

**Comment by joewilliams** [comment]
Ah, got it, thanks.
