### ISSUE TITLE
Latest build has random issues with window scroll

### ISSUE THREAD

**Issue by atr000** [MacIrssi/MacIrssi#29]
Using Version 0.8.6.6.327 (Build 8016ee5)

I'm noticing that sometimes windows when switching tabs will be a tiny bit up from the bottom part of the scroll, for no reason (not interacting via the mouse or keyboard) but then will not resume scrolling. I didn't recall this before.

Is there a keyboard shortcut (besides pagedown) to scroll al the way down or could something be a pref for scrolling down automatically?

I also noticed that multiline pastes seem to crash the client. I have not got it consistent yet but pasting from a browser, even a single line (150 chars) even did it. Would it be possible to truncate input into multilines if it's over 450 characters?

**Comment by ghost** [comment]
So scrolling artefacts are a bug in the new scrolling code introduced recently. I reworked that core today in 063a76bb365b76841e601c5a5fdb56f689552428 (and one bug in c6f3989b88d14056c6604a4ca5de7eecb5e25f29). So the next build that's cut should be much better.

Regarding crashing on paste, could you please paste a crash report into this issue? The only crash reports I have had sent in on 0.8.6.6.327 were likely to be unrelated to whatever you're seeing.

**Comment by atr000** [comment]
Had some issues reconnecting where the starting "location" was about halfway after ZNC dumped anywhere between a full screen to 500 lines, but im not seeing the "get stuck right above the active window" element anymore. 

I'll try and see if i can find some polluted content that breaks a "fuzz". 

On the char limit truncation, can this be done best by an internal perl script that splits into two on a long paste, or inside the client?

Also, on the Network and Server tab, one element missing on the Network side that is quite important with n+1 networks/ZNC is the password field. They fixed the bug on upstream back in March or so allowing multiple servers, even if on the same port but different username, to cooexist, since this is the only way many can use ZNC. I'm not sure if you intended to have something like this configured manually (works fine also)

**Comment by ghost** [comment]
You should be able to find the crash report for your paste problem in ~/Library/Logs/CrashReporter/MacIrssi*. Even if you can't properly reproduce it, the crash log would be helpful.

**Comment by ghost** [comment]
I suspect your crashes with pasting text might be to do with having ASCII as your default character set, then sending a command which included a non-ASCII character.

This is now no longer a problem, c9783d82e8301e7be474d4acbe72734a47f59dc1 removed the choice to choose character set and now forces UTF-8 at all times.

**Comment by atr000** [comment]
Looks good. THanks
