### ISSUE TITLE
Feature: Enable normal spellcheck on the inputbar?

### ISSUE THREAD

**Issue by atr000** [MacIrssi/MacIrssi#34]
I thought all "input" fields (NSTextInput) have it enabled?

**Comment by ghost** [comment]
It's definitely enabled in the beta. I think it's in the released version too but you can disable it via the Edit menu (and I think OS X keeps a record of it in preferences).

**Comment by atr000** [comment]
I noticed it is there but if you have "Check Spelling While Typing" (and also set via the nsuserdefaults for 10.6) it won't show up until I fire it (cmd+;). Never seen that before but it's also the first app I have w/o this being done automatically

**Comment by x3ro** [comment]
Works for me on 10.9. There's like a 1-2 second delay until it shows, but I think this is normal. Let me know if this is still causing problems for you.
