### ISSUE TITLE
Feature Request: Logging

### ISSUE THREAD

**Issue by Dakta** [MacIrssi/MacIrssi#35]
There is currently only one feature of MacIrssi that is really bugging me and that is logging. In many places it is common practice to keep logs of IRC channels, and having to manually copy/paste log channels is definitely a major PITA. I would support even the most simple implementation of logging, just writing the main chatbox output to a text file would be sufficient for me. I'd do it myself, but I haven't the necessary skills.

**Comment by ghost** [comment]
Logging already exists as part of the Irssi command set (refer to irssi.org for information on the underlying Irssi command set).

While MacIrssi doesn't expose these as UI elements you can still configure them using the slash commands.

**Comment by Dakta** [comment]
That is most excellent! Thanks man!
