### ISSUE TITLE
Automatically reconnecting spawns multiple connections to same server

### ISSUE THREAD

**Issue by nodoubleg** [MacIrssi/MacIrssi#37]
When switching between two different IP networks (such as wired & wireless) or when waking the Mac from sleep while MacIrssi is running, MacIrssi will automatically reconnect to any connections I had open.

It will also then spawn new connections to the same IRC servers.

I have both a Freenode server and an internal IRC server set to automatically connect upon startup.

I have just changed these two servers to not connect upon startup to see if that will serve as a workaround.

**Comment by nodoubleg** [comment]
Disabling "Connect automatically on startup" is not a workaround. Upon changing IP networks, MacIrssi will both reconnect the existing connections as well as spawn new ones.

**Comment by gogoduck** [comment]
Confirmed on wake from sleep.

With channels open, or with 'join channels' specified, it means clones are spawned to join those channels simultaneously so watch out.

**Comment by ghost** [comment]
I'm fairly sure this was fixed in 664b8fbc11c84a88fa4ec617c691f61e52adbd25, where I played with the reachability code quite a bit.
