### ISSUE TITLE
File->connection [server] mod

### ISSUE THREAD

**Issue by atr000** [MacIrssi/MacIrssi#38]
Could this be changed or set a preference so that the File->server name could reflect Network/something besides the IRC server? Using the ZNC->multiple connections to the same server makes it confusing with multiple connections since you can't tell which is which.

**Comment by ghost** [comment]
Latest beta's do exactly this. The File menu text now reads:

server [network]

Was fixed in e439999b77c10aa077b51802b2b65b381decffbf.
