### ISSUE TITLE
Using delete button without selection causes hangup

### ISSUE THREAD

**Issue by mikemansell** [MacIrssi/MacIrssi#41]
When in the network pane in the preferences menu, clicking on the "delete" button without selecting a network (amazingly I've managed to do this accidentally a few times) seems to confuse Macirssi, as it opens the delete confirmation dialog but doesn't allow you to submit or cancel it.  This means that one has to actually quit the application in order to get past the dialog.

Screenshot: http://cl.ly/1P1J3d1g051P0e3B033O

**Comment by ghost** [comment]
Oh dear, that's a rather poor show. Will fix that up next time in the source.
