### ISSUE TITLE
Submit MacIrssi to the AppStore

### ISSUE THREAD

**Issue by koliyo** [MacIrssi/MacIrssi#42]
The AppStore is likely to be the first place where users look for an IRC client to download, and it would be awesome if MacIrssi was represented there.

It could probably be submitted as-is? I have not looked closely at the submission guidelines.

Do you guys have a Mac developer account with Apple? If not I could supply an account to submit the application.

**Comment by ghost** [comment]
Sorry, it isn't going to happen any time soon. The AppStore and GPL don't play nice together. As has been shown with different applications on the iOS AppStore, GPL2's requirements on unrestricted redistribution and the AppStore don't work well together.

Further, I don't really want anyone else submitted it for me in my place as, ultimately, I'm currently responsible for the maintaining MacIrssi I don't want to have to deal with issues from the above as a result.
