### ISSUE TITLE
/SET indent not working

### ISSUE THREAD

**Issue by zmlka** [MacIrssi/MacIrssi#43]
_version_: Version 0.8.6.6.459 (44f8490)

Settings for [indent](http://irssi.org/documentation/settings#indent) are being rejected with `Unknown setting indent`.

I've tried both `/SET indent 10` and `/SET indent = 10` to the same result.

[Issue 31](https://github.com/daagaak/MacIrssi/issues/31) made me believe that this would have been working now, but it appears that in the latest beta it is not.

**Comment by ghost** [comment]
I'm not entirely sure which part of Issue 31 gave that impression; however, "/set indent" is part of the text-ui in irssi, a part of Irssi not included in MacIrssi because it implements it's own UI.

I doubt this ever worked in MacIrssi, nor will it, for the foreseeable future.

**Comment by zmlka** [comment]
Thanks for the reply.

regarding issue 31: I now realise that "(and also fixes indentation)" was referring to the indentation in the code, not the functionality.

Just want to thank you for this project, it's what has gotten me (for better or for worse) back on IRC after a few years off.

**Comment by ghost** [comment]
Thanks. I apologise I can't be more helpful here; I'm exceptionally busy with work these days and don't really have any energy left to work on MacIrssi. Thanks for the kind words though :).
