### ISSUE TITLE
Unable to join a channel that has "Ä" in its name

### ISSUE THREAD

**Issue by rikosnorsu** [MacIrssi/MacIrssi#45]
This is the problem I'm having with the newest version of MacIrssi. In older versions I was able to join this channel all my friends use in Quakenet but after updating to Lion I had also to update my MacIrssi and the latest release can't handle Ä's and Ö's in the channel name.

MacIrssi actually allows me to join the channel, but instead of taking me to the real channel, I end up being in a channel in the same network and the same name, but no other users but me (and I know there are others). All other channels work just fine, only the ones having ä-letters or ö-letters in their names are the problem.

Hopefully this is something that's easily fixed.

**Comment by x3ro** [comment]
I tried this on Quakenet using MacIrssi and the Quakenet Web IRC client joining the channel `#mörp`, and both ended up in the same channel. If this is still reproducible for you, please provide me with a server where this happens :)
