### ISSUE TITLE
Does it prevent standby?

### ISSUE THREAD

**Issue by tewe** [MacIrssi/MacIrssi#46]
When I leave the desk with MacIrssi running, and return hours later, it sometimes went to sleep (as it should) and sometimes ran through. Are there any deliberate measures for/against standby?

**Comment by ghost** [comment]
MacIrssi doesn't take any specific steps either way. However, your system won't sleep if the disk is not idle. So if logging is enabled in MacIrssi, or you have other applications that are constantly writing to disk then your device won't sleep.

**Comment by tewe** [comment]
Logging! Thanks!
