### ISSUE TITLE
Ability to build in Xcode 4 on Mac OS 10.7 Lion

### ISSUE THREAD

**Issue by pda** [MacIrssi/MacIrssi#47]
It doesn't seem possible to build MacIrssi in Xcode 4 on Mac OS 10.7.

Getting this working would enable contribution from the open source community. For example I'd like to try and improve the dock icon handing, but I have no hope of being able to build and test any changes I make. 

Thanks for MacIrssi!

Cheers,
Paul

**Comment by ghost** [comment]
The develop branch of MacIrssi builds just fine for me on 10.7 (and has done for many many months ;). Make sure you've checked out the submodules too, after switching to the develop branch.

**Comment by ghost** [comment]
(Just tried develop head and it's fine here. Let me know if you have further problems. Looking forward to looking at your ideas.)

**Comment by pda** [comment]
Ah thanks. I must have switched to 2e2f6aa227822b5cae73256c8ef25223835493cb at some point to compare something with latest released version 0.8.6.6.

The develop branch does indeed build and run fine :)

**Comment by ghost** [comment]
From what I remember of master, it's the old, horrid auto\* setup. Develop is completely Xcode based, and builds in a flash.

**Comment by pda** [comment]
Yep - zero configuration, built fast without hassle.
The master branch didn't even attempt to build, as it depends on Mac OS 10.4 frameworks that I don't have.
Time for a merge and release? :)
