### ISSUE TITLE
Support SSLv3/TLSv1

### ISSUE THREAD

**Issue by kennu** [MacIrssi/MacIrssi#49]
Ubuntu 11.10 / OpenSSL 1.0 have disabled SSLv2 support entirely, which causes stunnel4 to not accept connections from MacIrssi any more. MacIrssi seems to use SSLv2 exclusively.

I run an stunnel4 proxy with config like this:

; Protocol version (all, SSLv2, SSLv3, TLSv1)
sslVersion = TLSv1
[irc-ssl]
accept = 6668
connect = 127.0.0.1:6667

Since Ubuntu 11.10, the SSLv2 option can no longer be used.

**Comment by ghost** [comment]
What version of MacIrssi are you using? The 0.8.6.6.459 version in Github's downloads section uses SecureTransport for SSL and is set to allow all protocols _except_ SSLv2.

**Comment by kennu** [comment]
Thank you, I can confirm that it works. I was confused because I downloaded MacIrssi from somewhere earlier and "Check for updates" was saying "You're up to date".
