### ISSUE TITLE
MacIrssi hangs

### ISSUE THREAD

**Issue by benlemasurier** [MacIrssi/MacIrssi#52]
Running both stable and development release 0.8.6.6.459 (44f8490) I consistently run into what appears to be a deadlock. Here's the relevant stack trace: https://gist.github.com/1671090

**Comment by ghost** [comment]
Do you have steps to reproduce?

**Comment by benlemasurier** [comment]
No, apologies, I should have mentioned. I've been trying to track it down to a specific event however it seems to happen at random :\

My best guess would be after I've closed a private message, and the remote user sends another message. It's happened in other cases but this seems to be the most consistent case. Without _really_ knowing, the line `irc_parse_incoming` from the stack trace would also point at this behavior.

**Comment by x3ro** [comment]
Is this still happening to you?

**Comment by benlemasurier** [comment]
Years later, just came back to MacIrssi and haven't seen the problem.
