### ISSUE TITLE
Arabic Script

### ISSUE THREAD

**Issue by Obhur** [MacIrssi/MacIrssi#54]
Can you please put support for Arabic language. On IRC we can type in Arabic, but your client does not support arabic words. Me and all my friends report that we view arabic words in IRC channels as incomprehensible codes, and we ourselves cannot type in arabic nor chat.

Thank you

Obhur
obhur@ymail.com

**Comment by x3ro** [comment]
I couldn't reproduce this using the current nightly. I copied some arabic text from Wikipedia (hopefully nothing offensive), and it seems to display just fine:

![](http://cl.ly/image/181y2h0l211k/Screen%20Shot%202014-02-27%20at%2021.28.56.png)

If this is still happening to you, please describe the steps necessary to reproduce the issue.
