### ISSUE TITLE
channel encoding error

### ISSUE THREAD

**Issue by kInOzAwA** [MacIrssi/MacIrssi#55]
After change to UNICODE (UTF-16) there's no other way to turning back to switch to another channel encoding. pls help. I've uninstall it including cache and pref settings but there's no other way to fix.

**Comment by ghost** [comment]
This setting is stored in ~/.irssi/config and can be reset by either editing the file, or deleting it. Alternatively, the beta version available in downloads has already addresses this particular problem in the UI.
