### ISSUE TITLE
2014-02-06 nightly crashes on open

### ISSUE THREAD

**Issue by mzmcbride** [MacIrssi/MacIrssi#57]
I downloaded MacIrssi from http://x3ro.de/downloads/MacIrssi/ ("2014-02-06.zip" specifically). When I try to open the application, it immediately crashes. The associated diagnostic report is (in part):

<pre>
Process:         MacIrssi [74177]
Path:            /Applications/MacIrssi.app/Contents/MacOS/MacIrssi
Identifier:      uk.co.sysctl.MacIrssi
Version:         0.8.6.6 (0.8.6.6.467)
Code Type:       X86-64 (Native)
Parent Process:  launchd [135]
User ID:         501
Date/Time:       2014-02-24 23:34:32.124 -0500
OS Version:      Mac OS X 10.8.3 (12D78)
Crashed Thread:  0

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Symbol not found: ___sincos_stret
  Referenced from: /Applications/MacIrssi.app/Contents/MacOS/MacIrssi
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/MacIrssi.app/Contents/MacOS/MacIrssi
</pre>

I can provide the full diagnostic report via e-mail if you'd like.

Thanks for working on this project. I use the client daily. :-)

**Comment by x3ro** [comment]
I seem to have messed up build settings when upgrading project files to latest Xcode, setting Deployment Target instead of Base SDK to 10.9 :-1: I'll be uploading a new nightly build shortly, which hopefully fixes the issue. 

Edit: Check out http://x3ro.de/downloads/MacIrssi/2014-02-25.zip

**Comment by mzmcbride** [comment]
I tried http://x3ro.de/downloads/MacIrssi/MacIrssi-2014-02-28_01:26.tar.gz and it seems to not crash. Thanks!
