### ISSUE TITLE
Crashing upon joining a channel

### ISSUE THREAD

**Issue by legoktm** [MacIrssi/MacIrssi#58]
I was able to open a PM with a user (NickServ) fine, but when I tried joining the channel, the user joined the channel (as observed in my other IRC client), but it froze upon the loading screen and then crashed. The full error log is [here](https://gist.github.com/legoktm/c957b8c72dbb3a220d2d).

I am using the latest nightly, 2014-02-06.

**Comment by x3ro** [comment]
Thanks for trying out the nightly :smile: I can't really reproduce the issue, but I'll be uploading a new nightly build shortly, which doesn't have debugging symbols stripped, which hopefull will help to track down the issue. I suspect it's due to the update to irssi 0.8.16.

**Comment by x3ro** [comment]
Please try again with the latest nightly and re-post the crashlog :)

**Comment by legoktm** [comment]
I can't reproduce this anymore, thanks!
