### ISSUE TITLE
MacIrssi 2014-02-28 seems to not read user preferences

### ISSUE THREAD

**Issue by mzmcbride** [MacIrssi/MacIrssi#60]
I tried http://x3ro.de/downloads/MacIrssi/MacIrssi-2014-02-28_01:26.tar.gz and it seemed to read a fresh user preferences file.

Was the preferences file renamed? If so, can this be noted somewhere? Otherwise, perhaps this is a bug elsewhere? I'm not sure.

**Comment by x3ro** [comment]
I've set up build system for MacIrssi, and haven't noticed that it's building the project in development configuration, in which MacIrssi reads a separate debug config file. I'll have this fixed in the next nightly.
