### ISSUE TITLE
The "Window" and "Help" menus are missing

### ISSUE THREAD

**Issue by pratul** [MacIrssi/MacIrssi#8]
First up, I'm extremely glad to have found this repository :) The last time I checked the MacIrssi page on sysctl.co.uk, the repo was gone and the site was rather broken. Fortunately, I had the updated cloned git repo and I put it up on github.com/lut4rp/macirssi (in case someone would want to continue development). I planned to work on it some day myself. Thanks for continuing! (I should delete my clone now)

The actual issue is simple. MacIrssi does not have the Window or the Help menu.

(PS: Is there a mailing list/IRC channel where you do the development talk?)

**Comment by ghost** [comment]
So I'm planning to address the Mac OS inconsistencies pretty soon. It's always annoyed me that its missing the basic Mac OS X menu bars and items (and that there is no "Close" button on the main window).

We hang around in #macirssi on Quakenet if you want to join in. I don't have a mailing list, bugs are handled here mainly.

**Comment by ghost** [comment]
The develop branch has Window/Help menus now.
